### ISSUE TITLE
Chrome reporting "Virus Detected" when downloading release 0.1

### ISSUE THREAD

**Issue by DMacMakes** [ramdany7/RightClickFolderIconTools#1]
I'm using _Chrome 120.0.6099.71 (Official Build) (64-bit)_ on _Windows 10_, and I'm logged in to _Github_. I don't have any antivirus software installed beyond the built-in/Microsoft-issued Windows Defender. I visited the repo for RightClickFolderIconTools, clicked the latest release in the right nav ( RCFI Tools v0.1 ) in the right nav, clicked rcfi.tools.v.01.zip. It downloads, but the file never appears, and it warns me instead tha a virus was detected, next to a red download icon with a slash through it. See the attached image for the error, shown when I click the download icon on the right of the address bar (near the three-dot/kebab menu).

![error_virus_detected_rcfi-tools-v0-1-zip](https://github.com/ramdany7/RightClickFolderIconTools/assets/56147357/42ba2ff0-bbd2-46e2-9f84-7e72cc19945a)

**Comment by DMacMakes** [comment]
More info: I found the "Remediation" in "Windows Security -> Virus and threat protection", and it's taken exception to the RCFI Tools.bat file, having detected "Trojan:Win32/Vigorf.A". See the attached image for the full error.

![image](https://github.com/ramdany7/RightClickFolderIconTools/assets/56147357/144699a9-d0d3-4c32-a677-b37d7dad9aa0)

**Comment by ramdany7** [comment]
Oh, yeah, I've never noticed it.
Yes, it looks like some antivirus programs, including Windows Defender, might flag the "RCFI Tools.bat" as a malicious program. It never happened to me before, but when I do the same thing as you do by downloading it from the GitHub repo using Chrome, it gets detected. I think probably it's because I own the files, and they originated from my PC, so Windows never scanned it, or it's automatically trusted because I tried to scan it manually, and it still was not detected.

However, in regards to this case, I don't know what to do. I think the batch file will always be suspected as 'malicious,' especially when it has a thousand lines with some suspicious activities like:
- The shortcut function to search for the folder icon on the web/browser
- The function to call and interact with other programs to convert and edit the images
- The function to edit the registry to add the "Folder Icon Tools" to the Explorer context menu
- The function to read, write, copy, and delete the config files and temporary files
- The function to edit file attributes
- Etc.

Those might look too suspicious to antivirus for a batch script/batch file to do all of that.
So the only solution is probably to make an exception manually through the program/antivirus that blocked it from running to allow it.

**Comment by DMacMakes** [comment]
Thanks for the response 🙏 Maybe it's something to add to the README down the line. Head off more questions/issues.

**Comment by ramdany7** [comment]
yes, i will add it to the README. thank you for reporting the issue and thank you for the ⭐star. really appreciate it. 👍

**Comment by DMacMakes** [comment]
This issue no longer occurs on the more recent 0.3 release 👍
