### ISSUE TITLE
UNC paths not supported.

### ISSUE THREAD

**Issue by devanteweary** [ramdany7/RightClickFolderIconTools#12]
Hello!

Love this idea.

So my issue is all my movies and shows are on my network drive.

However I don't think cmd works with network paths.
I get the following....

![image](https://github.com/user-attachments/assets/07a56684-59b4-47c3-8b84-2266c3b52a79)

It says it did a couple folders but it didn't, and I have like 1,000+ folders.

Is there a way to get this working on a UNC path?

Thank you!

**Comment by ramdany7** [comment]
It appears that the script fails to change its working directory using the `cd /d` command and continues to generate icons in its own path. Unfortunately, I don’t have a network drive to test and experiment with, so I’m unsure if this issue can be resolved.

However, in this article '[[SOLVED] CMD does not support UNC paths as current directories](https://www.shellhacks.com/cmd-does-not-support-unc-paths-as-current-directories/),' it suggests that using the `pushd` command instead of `cd` might work. 

Would you mind trying this yourself by editing the script and replacing `cd /d` with `pushd`? 
I’ve already tested it on a local drive, and it worked fine.

here is the edited script I made just in case you are unsure how to do it: [RCFI Tools.zip](https://github.com/user-attachments/files/16229359/RCFI.Tools.zip)

**Comment by devanteweary** [comment]
> It appears that the script fails to change its working directory using the `cd /d` command and continues to generate icons in its own path. Unfortunately, I don’t have a network drive to test and experiment with, so I’m unsure if this issue can be resolved.
> 
> However, in this article '[[SOLVED] CMD does not support UNC paths as current directories](https://www.shellhacks.com/cmd-does-not-support-unc-paths-as-current-directories/),' it suggests that using the `pushd` command instead of `cd` might work.
> 
> Would you mind trying this yourself by editing the script and replacing `cd /d` with `pushd`? I’ve already tested it on a local drive, and it worked fine.
> 
> here is the edited script I made just in case you are unsure how to do it: [RCFI Tools.zip](https://github.com/user-attachments/files/16229359/RCFI.Tools.zip)

Wow thank you for not only the quick reply but also editing the script!!

OK here's what I did.

* Created Test folder.
* Copied a few movies into the Test folder.
* Right click empty space in Test folder > Generate from *Poster.jpg

Here's what happened.
First got a UNC error again. Then that window disappeared and the log showing it creating the icons popped up.

Here's what it looked like in screenshots:

![image](https://github.com/user-attachments/assets/c92d5e4e-94a9-4944-a45d-33391fca8dd5)

![image](https://github.com/user-attachments/assets/82138213-65fb-43c1-8734-d3deb107c939)

![image](https://github.com/user-attachments/assets/3948c7e9-350d-4ffa-adbb-1034606600f1)

Despite the UNC error, it seemed to work perfectly. Both enabling and removing the images/folder icons.
One thing though, it wasn't working at first. It'd create the image and desktop.ini but they wouldn't show up.
I found this is due to some bug that was introduced in a Windows security update.
A work around is enable the following in your regedit:

```
[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Explorer]
"EnableShellShortcutIconRemotePath"=dword:00000001
```

Last thing, love the verticle folder with no text... I can see you put the blur on the "tab half" of the folder.
Looks so good!

**Comment by ramdany7** [comment]
Awesome! Thanks for the details. Your explanation was very thorough, covering the conditions, the screenshots, the workaround for the problem, and everything ..

I guest I'll use `pushd` instead of `cd /d` for the future releases.
