### ISSUE TITLE
Feature Request: Add New Template

### ISSUE THREAD

**Issue by DemonSeedxp** [ramdany7/RightClickFolderIconTools#2]
I've been making my own folder icons as well as using lots of community made icons throughout my system, and I've looked for a tool such as this in the past but came up with very little aside from like folderico, but it had rather limited options so I never really used it.. 

![Screenshot 2024-03-29 202647](https://github.com/ramdany7/RightClickFolderIconTools/assets/11554194/acb3fdcf-c799-48ee-966d-1d8ed8f3e946)

But that means I currently have more folders with custom icons than without at this point, and I'd really like to keep the styling consistent hence why I've made so many myself  to fill gaps in the community made icons. 

So I got very excited when I discovered this tool and started checking it out, until I ran the sample images and realized the template being used for the horizontal folder is very different from the one based off the windows 11 vanilla folder that all my existing icons are built on.

Then I saw that this tool was utilizing predefined assets to generate its icons so I attempted to cheat and make my own assets with the same properties as the original ones were, but sadly that failed with the tool being unable to recognize the new assets and didn't render anything at all.       

So now I'm wondering if there is any way for me to achieve my goal, or if not request ither a way be added or easier still just having the assets I created be added as a second style perhaps? 

[Here's the files I made](https://github.com/ramdany7/RightClickFolderIconTools/files/14809481/Folder.Template.Images.zip) if just adding them might be easier. If they don't meet the requirements exactly just let me know and I can make any adjustments required if needed.

Thanks for your consideration.

**Comment by ramdany7** [comment]
Actually, I already made a Windows 11 template, but somehow I'm not satisfied enough with it, so I haven't added it yet to the repo. All this time, I have been searching for a "Windows 11 Folder Icon PSD template" for me to make a precise shape to use as a mask for editing using ImageMagick, but I haven't found any. So, I tried to make it myself.

The problem is, I don't know how to make it because I'm not good with Photoshop or any graphic design software. I just tried my best to replicate it, and it turned out to be like this: [Windows 11 Folder Icon Template.psd](https://github.com/ramdany7/RightClickFolderIconTools/files/14811317/Windows.11.Folder.Icon.Template.zip)

And here is the final result after doing some tricks using ImageMagick.
![Windows_11_Template](https://github.com/ramdany7/RightClickFolderIconTools/assets/113004105/5f0bbfcc-97e1-4005-b625-b6736c85e74e)

Here is the template if you want to tried it, 
[RCFI_Template_-_Windows_11.zip](https://github.com/ramdany7/RightClickFolderIconTools/files/14811193/RCFI_Template_-_Windows_11.zip)

And here is the "folder horizontal" if using your files (without repositioning/resizing the image and text).
[Folder Horizontal (custom).zip](https://github.com/ramdany7/RightClickFolderIconTools/files/14811592/Folder.Horizontal.custom.zip)

Right now, I'm thinking of adding an emboss or deboss effect to the generated image, but I haven't figured out yet how to do it using ImageMagick. So, for now, this is the best I can do. Let me know your thoughts on the Windows 11 template I've created above and how I can improve it, as I'm hesitant to share it since I feel it might not be good enough.

**Comment by DemonSeedxp** [comment]
Oh, I see, here is the psd that I work from if that'll help 
[Windows Folder Template.zip](https://github.com/ramdany7/RightClickFolderIconTools/files/14812863/Windows.Folder.Template.zip)

I do kinda get why you've help off releasing yours. I feel like the embossed edges are a bit over bearing. 

I'm not awesome with photoshop but I'm not awful with it either. I've used it for years. Funny enough I got into it for the very same reasons this tool exists, making icons to be displayed in a Media Center plugin called Media Browser. I got fairly decent with it back then as I shared my stuff with the community and it got insanely popular. I must have made thousands of requested icons by hand before I figured out photoshops scripting ability called Actions.  But what you've created here is soooo much better, what I wouldn't have given for something like this back in 2010, could have save me literal months of time. 

What's really funny is just how similar our works are, I honestly think I was the first to put the discs and the cases together in a media browser/xbmc/plex type program  

![Icon Samples](https://github.com/ramdany7/RightClickFolderIconTools/assets/11554194/3ec3313c-487d-4e82-995f-59069971c941)

![backdrop sample](https://github.com/ramdany7/RightClickFolderIconTools/assets/11554194/42ea82e9-5e92-4434-84ba-2fea9dfe1e69)

Pretty cool to see the trend still alive and well all these years later. 

All of that is to say that if there's anything I could assist you with or make for you in photoshop I'd happily be willing to try.
