### ISSUE TITLE
My own icon

### ISSUE THREAD

**Issue by BOBoneLivesHere** [ramdany7/RightClickFolderIconTools#3]
Is it possible to set the icon that is already present within the folder ?
I have tested your PNG to ICO converter to set the icon and I have found converted from your app looks little blurred as well as higher file size. Both are 256x256 with 32 bit depth
![Screenshot 2024-04-19 115553](https://github.com/ramdany7/RightClickFolderIconTools/assets/102818733/3eba6881-d62c-4e8b-aa69-09330dd7524e)

**Comment by ramdany7** [comment]
you can set .ico file that is already inside the folder.
to do that, set the Template to "**(none)**" then just right-click the .ico file you already have and then '**set as folder icon**'

by default if you set the **TemplateIconSize="Auto"** in the Configuration, it will convert any image to .ico with multiple icon size resources inside, which is: 16x16, 24x24, 32x32, 40x40, 48x48, 64x64, 96x96, 128x128, 192x192 and 256x256 so the file size will be bigger compared to only 256x256 .ico file without multiple icon size resources inside, you can extract all icon resources by converting .ico to .png. 

Converting methode i use here all is default configuration from ImageMagick, so maybe using other program that have more advanced algorithm or better configuration might have a better result.

if you want the output/generated .ico file to be smaller just set it to **TemplateIconSize="256"**, so it will only create a single 256x256 .ico file without any icon size resources inside.

**Comment by BOBoneLivesHere** [comment]
Just tested …
Template to "none" works, but it does convert my icon file to generate another icon file to use it with no visual difference
If duplicates found, I get some errors and sets the desktop.ini as temp in the end
in define keywords, the extension doesn't change with number input. But still got it working with config file
set as folder icon, still better than manual setting. But I didn't find a way to batch process it

In the end, it is a really awesome tool, and it does what it is supposed to do.
If any future updates comes ill test it out again
thanks for your hard work.

**Comment by ramdany7** [comment]
By using template "**(none)**", if the image is already .ico it will only copy and then rename the file so there will be no visual difference. If the image is .png or anything else it will resize the image and set the canvas aspect ratio to 1:1 then convert it to .ico file.

Yes, there's a bug where the extension doesn't change in 'define keywords' features. I've already made some changes to the script to fix that. It will be fixed in v0.2 release, which is not ready yet. However, you can already try it by uninstalling the previous version and replacing the script with the latest modified version: [RCFI Tools.bat](https://github.com/ramdany7/RightClickFolderIconTools/blob/main/RCFI%20Tools.bat)

![Screenshot_484](https://github.com/ramdany7/RightClickFolderIconTools/assets/113004105/0d1309dd-5ec2-4056-9303-bea301ef75f1)

As for now, I don't know yet how to achieve a better result in the converted file. So, yeah, you have to convert it on your own. Thank you for the input; I'm happy someone is noticing my work.
